### ISSUE TITLE
CI fails

### ISSUE THREAD

**Issue by MikeMcC399** [bahmutov/cypress-examples#137]
## Problem description

CI fails. See https://github.com/bahmutov/cypress-examples/actions/workflows/ci.yml, for example run [3976367744](https://github.com/bahmutov/cypress-examples/actions/runs/3976367744)

The job `test-js` fails. See also record in Cypress Cloud https://cloud.cypress.io/projects/dis6wg/runs/1191/specs

**Comment by bahmutov** [comment]
Need to figure it out. Why are there double slashes
![image](https://user-images.githubusercontent.com/2212006/215168664-898da434-1d74-4052-884b-183e54dcc533.png)

![Screen Shot 2023-01-27 at 13 40 59](https://user-images.githubusercontent.com/2212006/215168689-9aa95e40-68a9-43be-a998-2907e6b5640e.png)

**Comment by bahmutov** [comment]
will skip testing JS for now

**Comment by MikeMcC399** [comment]
Closing, since it no longer fails.

It does however produce many deprecation warnings, which should be addressed.
