### ISSUE TITLE
Assert that text is not visible, whether present in DOM or not

### ISSUE THREAD

**Issue by dandavison** [bahmutov/cypress-examples#69]
From [gitter](https://gitter.im/cypress-io/cypress?at=602406395500a97f82fb90ad):

![image](https://user-images.githubusercontent.com/52205/107540635-4280c800-6b94-11eb-9944-9155351af7ee.png)
![image](https://user-images.githubusercontent.com/52205/107540665-49a7d600-6b94-11eb-8955-c076dc775ece.png)

 http://on.cypress.io/dom#is-visible

**Comment by bahmutov** [comment]
Soon will be deployed, for now this is how it works:

<img width="1015" alt="Screen Shot 2021-02-10 at 12 16 50 PM" src="https://user-images.githubusercontent.com/2212006/107546083-f8024a00-6b99-11eb-84e7-67c87df8fb0b.png">
