### ISSUE TITLE
Make sure every page has all existing tests

### ISSUE THREAD

**Issue by bahmutov** [bahmutov/cypress-examples#8]
Look at the Kitchensink **repo** to make sure our markdown has all tests. Kitchensink online might be behind the tests in the repo

- [x] Quering
- [x] Traversal
- [x] Actions @CypressCecelia 
- [x] Window
- [x] Viewport
- [x] Location
- [x] Navigation
- [x] Assertions
- [x] Misc
- [x] Connectors @CypressCecelia 
- [x] Aliasing
- [x] Waiting
- [x] Network Requests
- [x] Files
- [x] Cookies
- [x] Spies, Stubs & Clocks
- [x] Utilities
- [x] Cypress API

**Comment by CypressCecelia** [comment]
pushed actions-page but have some failing tests to debug.

**Comment by bahmutov** [comment]
All done
